### ISSUE TITLE
"Edit members of <User Group>" could use some love.

### ISSUE THREAD

**Issue by kiriwalawren** [Arezhik/slackCustomCSS#4]
The names here are too light and therefore hard to read. It might also be nice to have the blue background of the names match the color scheme (but that is just a plus).
![image](https://user-images.githubusercontent.com/6665964/34631869-b8a7e504-f22f-11e7-9472-ed8b4bed7328.png)

**Comment by Arezhik** [comment]
K I will look into it. Thanks!

**Comment by Arezhik** [comment]
Resolved background coloring by setting it to the global color scheme #222. Makes for easier readability. Fix another problem with the input box being completely black; switched it to #222 color.

Added the save button to button layout which adds a border. 
Added "Create A New Group" button to button layout as well.
