### ISSUE TITLE
Sections of main window do not conform to color scheme.

### ISSUE THREAD

**Issue by kiriwalawren** [Arezhik/slackCustomCSS#8]
Date Header and Scroll Bar do not conform to the color scheme:
![image](https://user-images.githubusercontent.com/6665964/35167359-74045d7c-fd12-11e7-9fc6-0c166b3e2377.png)
![image](https://user-images.githubusercontent.com/6665964/35167390-9a6d8cc2-fd12-11e7-9d7c-97cdc9887105.png)

In the above images, my primary color is set to #d81c1c

**Comment by kiriwalawren** [comment]
Same thing with the "More Actions" bar that shows up when hovering over a message.
![image](https://user-images.githubusercontent.com/6665964/35168499-669af3c2-fd16-11e7-8f57-de309f2f9aed.png)

**Comment by kiriwalawren** [comment]
And @ tags.
![image](https://user-images.githubusercontent.com/6665964/35168984-1680ba8c-fd18-11e7-90f2-e0c834db9a9b.png)

**Comment by Arezhik** [comment]
So do you want the date dividers and pills borders to conform to the primary colors?

i.e. - They would become red once you changed the primary color as you have done in the images?

**Comment by Arezhik** [comment]
Fixed several of the issues in the latest build in master. Will start identifying and working on others...
